import os
import chromadb
import random
from chromadb.api.types import Documents, EmbeddingFunction, Embeddings
from google import genai
from google.genai import types
from dotenv import load_dotenv, find_dotenv

load_dotenv(find_dotenv(), override=True)
"""
Generated By Gemini 3 Pro
"""


class GeminiEmbeddingFunction(EmbeddingFunction):
    def __init__(self):
        self.client = genai.Client(api_key=os.environ.get("GOOGLE_API_KEY"))

    def __call__(self, input: Documents) -> Embeddings:
        embeddings = []
        for text in input:
            response = self.client.models.embed_content(
                model='gemini-embedding-001',
                contents=text,
                config=types.EmbedContentConfig(
                    task_type="RETRIEVAL_QUERY"
                )
            )
            embeddings.append(response.embeddings[0].values)
        return embeddings

class ChromaConnector:
    def __init__(self, path=None, collection_name="guardian_chunks"):
        if path is None:
            current_dir = os.path.dirname(os.path.realpath(__file__))
            generator_dir = os.path.dirname(current_dir)
            root_dir = os.path.dirname(generator_dir)
            path = os.path.join(root_dir, "data/chroma_data")
        self.gemini_client = genai.Client(api_key=os.environ.get("GOOGLE_API_KEY"))

        self.client = chromadb.PersistentClient(path=path)
        self.collection = self.client.get_collection(name=collection_name)

    def get_gemini_embedding(self, text):
        """Erzeugt manuell das 3072-dimensionale Embedding für die Suche"""
        response = self.gemini_client.models.embed_content(
            model='gemini-embedding-001',
            contents=text,
            config=types.EmbedContentConfig(
                task_type="RETRIEVAL_QUERY"
            )
        )
        return response.embeddings[0].values

    def get_random_chunk(self):
        total_chunks = self.collection.count()
        if total_chunks == 0:
            return None

        random_idx = random.randint(0, total_chunks - 1)
        results = self.collection.get(
            include=['metadatas', 'documents'],
            limit=1,
            offset=random_idx
        )

        if not results['ids']:
            return None

        return {
            'id': results['ids'][0],
            'text_snippet': results['documents'][0],
            'article_id': results['metadatas'][0]['article_id'],
            'chunk_index': results['metadatas'][0]['chunk_index']
        }

    def get_bridging_chunk(self, query_text, exclude_article_id, top_k=5):
        """Steps 2 & 3: Filtered Semantic Search & Randomised Selection (d_B)"""

        query_vector = self.get_gemini_embedding(query_text)

        results = self.collection.query(
            query_embeddings=[query_vector],
            n_results=top_k,
            where={"article_id": {"$ne": exclude_article_id}}
        )

        if not results['ids'] or not results['ids'][0]:
            return None

        idx = random.randint(0, len(results['ids'][0]) - 1)
        return {
            'id': results['ids'][0][idx],
            'text_snippet': results['documents'][0][idx],
            'article_id': results['metadatas'][0][idx]['article_id'],
            'chunk_index': results['metadatas'][0][idx]['chunk_index']
        }

    def get_intra_document_chunk(self, article_id, exclude_chunk_indices):
        """For Turn > 1: Get new chunk from same article"""
        results = self.collection.get(
            where={"article_id": article_id},
            include=['metadatas', 'documents']
        )

        valid_indices = [
            i for i, meta in enumerate(results['metadatas'])
            if meta['chunk_index'] not in exclude_chunk_indices
        ]

        if not valid_indices:
            return None

        idx = random.choice(valid_indices)
        return {
            'id': results['ids'][idx],
            'text_snippet': results['documents'][idx],
            'article_id': results['metadatas'][idx]['article_id'],
            'chunk_index': results['metadatas'][idx]['chunk_index']
        }

    def get_adjacent_chunk(self, article_id, current_indices, total_chunks, direction="below"):
        """
        Retrieves the adjacent document chunk based on the preferred semantic direction.
        Automatically reverses direction if a document boundary is reached.

        Args:
            article_id: The parent document identifier.
            current_indices: A list of chunk indices currently in the active context.
            total_chunks: The total number of chunks in the parent document.
            direction: The preferred expansion direction ('above' or 'below').

        Returns:
            The adjacent chunk dictionary, or None if the document is fully loaded.
        """
        if len(current_indices) >= total_chunks:
            return None

        min_idx = min(current_indices)
        max_idx = max(current_indices)

        target_idx = None

        if direction == "below":
            if max_idx + 1 < total_chunks:
                target_idx = max_idx + 1
            elif min_idx - 1 >= 0:
                target_idx = min_idx - 1
        elif direction == "above":
            if min_idx - 1 >= 0:
                target_idx = min_idx - 1
            elif max_idx + 1 < total_chunks:
                target_idx = max_idx + 1

        if target_idx is None:
            return None

        results = self.collection.get(
            where={"$and": [{"article_id": article_id}, {"chunk_index": target_idx}]},
            include=['metadatas', 'documents']
        )

        if not results['ids']:
            return None

        return {
            'id': results['ids'][0],
            'text_snippet': results['documents'][0],
            'article_id': results['metadatas'][0]['article_id'],
            'chunk_index': results['metadatas'][0]['chunk_index'],
            'total_chunks': results['metadatas'][0].get('total_chunks', total_chunks)
        }

    def get_chunk_by_id(self, article_id, chunk_index):
        """Retrieve a specific chunk by article_id and chunk_index."""
        results = self.collection.get(
            where={"$and": [{"article_id": article_id}, {"chunk_index": chunk_index}]},
            include=['metadatas', 'documents']
        )

        if not results['ids']:
            return None

        return {
            'id': results['ids'][0],
            'text_snippet': results['documents'][0],
            'article_id': results['metadatas'][0]['article_id'],
            'chunk_index': results['metadatas'][0]['chunk_index'],
            'total_chunks': results['metadatas'][0].get('total_chunks', 1)
        }


    #ToDo remove later
    def get_chunk_by_id_for_streamlit(self, chunk_id):
        results = self.collection.get(ids=[chunk_id], include=['documents'])
        return results['documents'][0] if results['documents'] else None