import os
import chromadb
import random
from chromadb.api.types import Documents, EmbeddingFunction, Embeddings
from google import genai
from google.genai import types
from dotenv import load_dotenv

load_dotenv(override=True)
"""
Generated By Gemini 3 Pro
"""


class GeminiEmbeddingFunction(EmbeddingFunction):
    def __init__(self):
        self.client = genai.Client(api_key=os.environ.get("GOOGLE_API_KEY"))

    def __call__(self, input: Documents) -> Embeddings:
        embeddings = []
        for text in input:
            response = self.client.models.embed_content(
                model='gemini-embedding-001',
                contents=text,
                config=types.EmbedContentConfig(
                    task_type="RETRIEVAL_QUERY"
                )
            )
            embeddings.append(response.embeddings[0].values)
        return embeddings

class ChromaConnector:
    def __init__(self, path=None, collection_name="guardian_chunks"):
        if path is None:
            current_dir = os.path.dirname(os.path.realpath(__file__))
            generator_dir = os.path.dirname(current_dir)
            root_dir = os.path.dirname(generator_dir)
            path = os.path.join(root_dir, "data/chroma_data")
        self.gemini_client = genai.Client(api_key=os.environ.get("GOOGLE_API_KEY"))

        self.client = chromadb.PersistentClient(path=path)
        self.collection = self.client.get_collection(name=collection_name)

    def get_gemini_embedding(self, text):
        """Erzeugt manuell das 3072-dimensionale Embedding für die Suche"""
        response = self.gemini_client.models.embed_content(
            model='gemini-embedding-001',
            contents=text,
            config=types.EmbedContentConfig(
                task_type="RETRIEVAL_QUERY"
            )
        )
        return response.embeddings[0].values

    def get_random_chunk(self):
        total_chunks = self.collection.count()
        if total_chunks == 0:
            return None

        random_idx = random.randint(0, total_chunks - 1)
        results = self.collection.get(
            include=['metadatas', 'documents'],
            limit=1,
            offset=random_idx
        )

        if not results['ids']:
            return None

        return {
            'id': results['ids'][0],
            'text_snippet': results['documents'][0],
            'article_id': results['metadatas'][0]['article_id'],
            'chunk_index': results['metadatas'][0]['chunk_index']
        }

    def get_bridging_chunk(self, query_text, exclude_article_id, top_k=5):
        """Steps 2 & 3: Filtered Semantic Search & Randomised Selection (d_B)"""

        # 3. Wir übersetzen den Text manuell in den 3072-Vektor!
        query_vector = self.get_gemini_embedding(query_text)

        # 4. Wir suchen mit query_embeddings anstatt query_texts!
        results = self.collection.query(
            query_embeddings=[query_vector],
            n_results=top_k,
            where={"article_id": {"$ne": exclude_article_id}}
        )

        if not results['ids'] or not results['ids'][0]:
            return None

        idx = random.randint(0, len(results['ids'][0]) - 1)
        return {
            'id': results['ids'][0][idx],
            'text_snippet': results['documents'][0][idx],
            'article_id': results['metadatas'][0][idx]['article_id'],
            'chunk_index': results['metadatas'][0][idx]['chunk_index']
        }

    def get_intra_document_chunk(self, article_id, exclude_chunk_indices):
        """For Turn > 1: Get new chunk from same article"""
        results = self.collection.get(
            where={"article_id": article_id},
            include=['metadatas', 'documents']
        )

        valid_indices = [
            i for i, meta in enumerate(results['metadatas'])
            if meta['chunk_index'] not in exclude_chunk_indices
        ]

        if not valid_indices:
            return None

        idx = random.choice(valid_indices)
        return {
            'id': results['ids'][idx],
            'text_snippet': results['documents'][idx],
            'article_id': results['metadatas'][idx]['article_id'],
            'chunk_index': results['metadatas'][idx]['chunk_index']
        }