version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: guardian_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  guardian_fetcher:
    build: .
    container_name: guardian_fetcher
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./container-logs:/logs
    env_file:
      - .env

volumes:
  mongo_data: